version: "2.1"
services:
  opbeans-node:
    extends:
      file: docker-compose.yml
      service: opbeans-node
      
  apm-server:
    extends:
      file: docker-compose.yml
      service: apm-server
    command: >
      apm-server -e
        -E apm-server.frontend.enabled=true
        -E apm-server.frontend.rate_limit=100000
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.read_timeout=1m
        -E apm-server.shutdown_timeout=2m
        -E apm-server.write_timeout=1m
        -E apm-server.rum.enabled=true
        -E setup.template.settings.index.number_of_replicas=0
        -E xpack.monitoring.elasticsearch=true
        -E cloud.id=${ELASTIC_CLOUD_ID}
        -E cloud.auth=${ELASTIC_CLOUD_CREDENTIALS}
      
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
      
  redis:
    extends:
      file: docker-compose.yml
      service: redis
      
  wait:
    extends:
      file: docker-compose.yml
      service: wait
      
  loadPgData:
    extends:
      file: docker-compose.yml
      service: loadPgData
        
volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
